In [7]:
import torch
from transformers import Wav2Vec2Model

In [14]:
# Loaidng the pretrained model
model = Wav2Vec2Model.from_pretrained("facebook/wav2vec2-xls-r-2b")

Base model is updated uning this checkpoint

In [19]:
checkpoint_path = "/scratch/IITB/ai-at-ieor/23m1508/23m1508_backup/checkpoint_points/weights_535000_545000/multilingual_asr_model_535000_545000.pt"

In [20]:
#######################################
# Use only one time since in this i have extatct the first 48 layers weights


checkpoint = torch.load(checkpoint_path, map_location = "cpu", weights_only = False)
    
state_dict = checkpoint['model_state_dict']  # 

In [26]:
checkpoint

{'epoch': 145,
 'model_state_dict': OrderedDict([('projector.wav2vec2.masked_spec_embed',
               tensor([ 0.2486,  0.2312,  0.3772,  ..., -0.0480,  0.1279,  0.4455])),
              ('projector.wav2vec2.feature_extractor.conv_layers.0.conv.weight',
               tensor([[[ 0.3312, -0.1804,  0.0012,  ...,  0.2414, -0.0308, -0.4248]],
               
                       [[-0.5214,  0.1165,  0.1743,  ...,  0.4653, -0.5165,  0.0486]],
               
                       [[-0.1909,  0.3462, -0.5351,  ...,  0.3851, -0.2954, -0.2443]],
               
                       ...,
               
                       [[-0.4140,  0.3962, -0.5326,  ..., -0.0636,  0.0577,  0.2435]],
               
                       [[ 0.1464,  0.2354,  0.4323,  ..., -0.5460, -0.3212,  0.1279]],
               
                       [[ 0.1127, -0.3622,  0.4366,  ..., -0.3992, -0.2054,  0.3327]]])),
              ('projector.wav2vec2.feature_extractor.conv_layers.0.conv.bias',
               

In [21]:
base_model_state_dict = {
k.replace("projector.wav2vec2.", ""): v
for k, v in state_dict.items()
if k.startswith("projector.wav2vec2.")
}

# print('The keys of the base model state dict are :', base_model_state_dict.keys())

In [23]:


missing, unexpected = model.load_state_dict(base_model_state_dict, strict = False)

print("Missing keys (likely your new CTC heads or projector):", missing)
print("Unexpected keys (should be empty):", unexpected)

Missing keys (likely your new CTC heads or projector): []
Unexpected keys (should be empty): []


In [24]:
import os
base_model_save_path = os.path.join("/scratch/IITB/ai-at-ieor/23m1508/23m1508_backup/checkpoint_points/updated_base_model_weights", 
                                    "updated_base_wav2vec2_model_1.pt")

In [25]:
torch.save({
    'model_state_dict': model.state_dict(),
}, base_model_save_path)

In [27]:
m = torch.load("/scratch/IITB/ai-at-ieor/23m1508/23m1508_backup/checkpoint_points/updated_base_model_weights/updated_base_wav2vec2_model_1.pt", map_location = "cpu", weights_only = False)

In [28]:
m

{'model_state_dict': OrderedDict([('masked_spec_embed',
               tensor([ 0.2486,  0.2312,  0.3772,  ..., -0.0480,  0.1279,  0.4455])),
              ('feature_extractor.conv_layers.0.conv.weight',
               tensor([[[ 0.3312, -0.1804,  0.0012,  ...,  0.2414, -0.0308, -0.4248]],
               
                       [[-0.5214,  0.1165,  0.1743,  ...,  0.4653, -0.5165,  0.0486]],
               
                       [[-0.1909,  0.3462, -0.5351,  ...,  0.3851, -0.2954, -0.2443]],
               
                       ...,
               
                       [[-0.4140,  0.3962, -0.5326,  ..., -0.0636,  0.0577,  0.2435]],
               
                       [[ 0.1464,  0.2354,  0.4323,  ..., -0.5460, -0.3212,  0.1279]],
               
                       [[ 0.1127, -0.3622,  0.4366,  ..., -0.3992, -0.2054,  0.3327]]])),
              ('feature_extractor.conv_layers.0.conv.bias',
               tensor([ 0.0248,  0.0237,  0.0365, -0.2166,  0.0438,  0.1045,  0.1225, -